// Generated by CoffeeScript 1.7.1
'use strict';
requirejs.config({
  paths: {
    jquery: "http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min"
  }
});

define(['jquery', 'sinon'], function($, sinon) {
  var ajax;
  ajax = function() {
    return 'ajax call';
  };
  ajax.endpoint = function(url) {
    var req;
    req = $.ajax({
      url: url
    });
    req.done(function(e) {
      return e;
    });
    return url;
  };
  ajax.setup = function(arg) {
    var setup, url, _ref;
    url = arg.url || '';
    setup = (function() {
      return $.ajaxSetup = {
        url: url
      };
    })();
    return (_ref = arg.url) != null ? _ref : arg;
  };
  return {
    ajax: ajax,
    endpoint: ajax.endpoint,
    setup: ajax.setup
  };
});
